name = "CivFun-Client"
author = "Klari"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1dffe4e6a4baf26852a6598d2240e3947f2bd054f300664ebd295d4dc617137"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
