name = "CivFun-Client"
author = "Klari"
version = "0.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "687de444b55f01299365cde4a56b16f19777c4fe13491f099b94ac0489c28dd8"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"

[options]
datapack-folder = "config/openloader/data"
