name = "CivFun-Client"
author = "Klari"
version = "0.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa272769c5efd303f5422d74e91fcd0f4895d26d8fdb0e0ba6167b33a1b78dda"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"

[options]
datapack-folder = "config/openloader/data"
