name = "CivFun-Client"
author = "Klari"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15cfe8aae5ae6bc463d18545ae947a2176654b5472498236200e1dd5c58e6855"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"

[options]
datapack-folder = "config/openloader/data"
