name = "CivFun-Client"
author = "Klari"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8688b5ccb5467b641d749b81c26a06320229e8c9cc2d9ad9b86b279d804ebe7a"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"

[options]
datapack-folder = "config/openloader/data"
